# Generated by Django 5.0.6 on 2024-06-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('content', models.BinaryField()),
                ('upload_date', models.DateTimeField(verbose_name='date uploaded')),
            ],
        ),
    ]
