# Generated by Django 5.0.6 on 2024-06-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='content',
            field=models.BinaryField(max_length=1000000),
        ),
    ]
